package com.example.kotlinmvvm.bean

data class VideoBean(
    val bigcover: String,
    val boutique: Int,
    val cover: String,
    val daren: Int,
    val desc: String,
    val display: Int,
    val duration: Double,
    val favorite: Int,
    val flv: String,
    val gameicon: String,
    val gamename: String,
    val gametype: Int,
    val headicon: String,
    val horizontal: Int,
    val mp4: String,
    val mp4_res: List<String>,
    val mp4_url: String,
    val nickname: String,
    val panorama: Int,
    val praise: Int,
    val priv_vip_level: Int,
    val ptype: Int,
    val purl: String,
    val pv: Int,
    val recordid: String,
    val src: String,
    val state: Int,
    val tag: String,
    val title: String,
    val top: Int,
    val uid: Int,
    val uploadtime: String
)